# Generated by Django 2.1.5 on 2022-09-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('buy_in', models.DecimalField(decimal_places=2, max_digits=12)),
                ('players', models.IntegerField(blank=True, null=True)),
                ('prizepool', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('compleated', 'compleated'), ('running', 'running'), ('late reg', 'late reg'), ('upcoming', 'upcoming')], max_length=30)),
                ('type', models.CharField(choices=[('freezout', 'freezout'), ('R&A', 'R&A'), ('PKO', 'PKO'), ('Knockot', 'Knockout')], max_length=30)),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
    ]
