# Generated by Django 2.1.5 on 2022-09-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
