# Generated by Django 2.1.5 on 2022-09-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='game_type',
            field=models.CharField(blank=True, choices=[('Tournaments', 'Tournaments'), ('Cash Games', 'Cash Games'), ('Sit % Go', 'Sit & Go'), ('Spins', 'Spins')], max_length=30),
        ),
    ]
