# Generated by Django 2.1.5 on 2022-09-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournaments_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='game_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Game_Type'),
        ),
    ]
