# Generated by Django 2.1.5 on 2022-09-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_cash_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_games',
            name='prices',
            field=models.CharField(max_length=50),
        ),
    ]
