# Generated by Django 2.1.5 on 2022-09-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_auto_20220909_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sit_Go',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('players', models.CharField(max_length=50)),
                ('buy_in', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('registering', 'registering'), ('running', 'running')], max_length=30)),
                ('game_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Game_Type')),
            ],
            options={
                'verbose_name': 'Sit & Go',
                'verbose_name_plural': 'Sit & Go',
            },
        ),
    ]
