# Generated by Django 2.1.5 on 2022-09-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_sit_go'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_in', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_prizepool', models.DecimalField(decimal_places=2, max_digits=12)),
                ('blind_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Spin',
                'verbose_name_plural': 'Spins',
            },
        ),
    ]
