# Generated by Django 2.1.5 on 2022-09-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_spin'),
    ]

    operations = [
        migrations.AddField(
            model_name='spin',
            name='name',
            field=models.CharField(default='BLAST', max_length=50),
        ),
    ]
